export const metadata = {
    title: {
      default: "Nosotros", 
    },
    description: "Generated by create next app",
  };


export default function Layout({ children }) {
  return (
    <>
     <main>{children}</main>
    </>
  )
}
