import Cardiopatia from '@/components/Cardiopatia';
import Galería from '@/components/Galería';
import React from 'react'
export const metadata = {
    title: {
      default: "Solucion", 
    },
    description: "Generated by create next app",
  };

export default function page() {
  return (
    <>
    <div>
        <Cardiopatia>
            
        </Cardiopatia>
    </div>
    </>
  )
}
