import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Menu from "@/components/Menu";
import { montserrat } from "./ui/fonts";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

  export const metadata = {
    title: {
      default: "Médicos Sideral Carrión", 
      template:"%s | Médicos Sideral Carrión" 
    },
    description: "Generated by create next app",
  };

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body
        className={`${montserrat.className}  antialiased`} 
      >
        <Menu></Menu>
        
        {children}
        <Footer></Footer>
      </body>
    </html>
  );
}
