import CsvCardiopatia from "@/components/CsvCardiopatia";

export const metadata = {
    title: {
      default: "Ranking clinico", 
    },
    description: "Generated by create next app",
  };
  
  export default function page() {
    return (
      <div>
        <CsvCardiopatia>

        </CsvCardiopatia>
      </div>
    )
  }
  