
import {
    Card,
    CardContent,
    CardDescription,
    CardFooter,
    CardHeader,
    CardTitle,
} from "@/components/ui/card"

export const metadata = {
    title: {
        default: "Bibliografia",
    },
    description: "Generated by create next app",
};
const fuentes = [{
    title: "Organización Mundial de la Salud. (2025).",
    description: "Enfermedades cardiovasculares",
    link: "https://www.who.int/es/health-topics/cardiovascular-diseases#tab=tab_1"

}, 

]

export default function page() {
    return (
        <div className=" ml-20 mr-20 mt-10">
            {fuentes.map((fuente, index) => (
                <Card key={index} className="mt-5">
                    <CardHeader>
                        <CardTitle>{fuente.title}</CardTitle>
                        <CardDescription>{fuente.description}</CardDescription>
                    </CardHeader>
                    <CardContent>
                    <a
                        href={fuente.link}
                        target="_blank"
                        rel="noopener noreferrer"
                    > Enlace
                    </a>
                    </CardContent>
                    

                </Card>
            ))}

        </div>
    )
}
